### ISSUE TITLE
more detailed feedback

### ISSUE THREAD

**Issue by Medienkunzt** [thm-mnd-ii/eWiLL#123]
When specifying the feedback, the following additional information should be collected: FirstName, LastName, DateTime, Status (NotReviewed,ToDo,WontFix,Fixed).

Also the deletion route is missing.
Furthermore it should be possible to change the status of a feedback.

**Comment by LwTuna** [comment]
Need to change the create route to send a json object with the details instead of a "plain/text" string

**Comment by LwTuna** [comment]
Routes for deleting/updating and getting all status added, can be implemented into the frontend
