### ISSUE TITLE
[Epic] Checker API v1

### ISSUE THREAD

**Issue by Medienkunzt** [thm-mnd-ii/eWiLL#42]
Currently there is no possibility to check diagrams (SERM) for correctness.

Therefore the first version of a checker API will be developed.
The Checker API is responsible for checking a diagram by comparing it with one or more sample solutions.

_**Later on, the checker API and the frontend functionalities will be integrated into the feedback system.
Therefore, all interfaces should be designed to be integrated into the feedback system.**_

### Backend Tickets
- [ ] ...

### Frontend Tickets
- [ ] Create the necessary web components to allow users to create, save, edit and delete models.
- [ ] Create the necessary web components to allow administrators to create courses in which they define multiple tasks.

**Comment by LwTuna** [comment]
Outdated
