### ISSUE TITLE
Mockup: new approach on task creation

### ISSUE THREAD

**Issue by Medienkunzt** [thm-mnd-ii/eWiLL#44]
In the feedback system, the current concept of courses, tasks and task configurations is very much based on files and text. This is not the case for model evaluation. Therefore we try to develop a new approach for the creation of tasks.
We try to adapt and further develop the data structure from the feedback system.

The new representation will be created as a mockup.
It will contain all necessary windows for creating, reading, updating and deleting courses, tasks and configurations.

**Comment by LwTuna** [comment]
Task System maybe needs a rework later, but until then this ticket is closed
