### ISSUE TITLE
Create build pipeline

### ISSUE THREAD

**Issue by Medienkunzt** [thm-mnd-ii/eWiLL#5]
Create build pipeline w/ Docker-Compose
- [ ] deploy frontend
- [ ] deploy api
- [ ] add documentation to README.md

With this feature it shoud be possible to run `docker compose up -d --build` in the main directory, to build the projekt locally
Hide Passwords, configurations, etc with enviroment variables like $$MYSQL_ROOT_PASSWORD

**Comment by LwTuna** [comment]
Obsolte of #99
